# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BiaoGe1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_biaoge1(object):
    def setupUi(self, Form_biaoge1):
        Form_biaoge1.setObjectName("Form_biaoge1")
        Form_biaoge1.resize(1132, 547)
        self.gridLayout = QtWidgets.QGridLayout(Form_biaoge1)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form_biaoge1)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(708, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(Form_biaoge1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Form_biaoge1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form_biaoge1)
        QtCore.QMetaObject.connectSlotsByName(Form_biaoge1)

    def retranslateUi(self, Form_biaoge1):
        _translate = QtCore.QCoreApplication.translate
        Form_biaoge1.setWindowTitle(_translate("Form_biaoge1", "Form"))
        self.pushButton.setText(_translate("Form_biaoge1", "第一页"))
        self.pushButton_2.setText(_translate("Form_biaoge1", "第二页"))
